# The URL the site will be built for
base_url = "https://nolik.github.io/blog"

title = "Ihar Novik"
# a description; you can use markdown here if you like
description="\"What's the best thing thing about UDP jokes? ... I don't care if you get them\""
default_language = "en"

highlight_theme = "solarized-light"

generate_rss = false

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]
subtitle = "Software engineer passionate about Java and Rust"

# theme options, (Submit an issue if any social network you may want is missing here: https://github.com/InsidiousMind/Ergo/issues)
profile = "profile.svg" # the name of the profile picture in static/img/
github = "nolik"
linkedin = "ihar-novik"
email = "nolik03@gmail.com"
# website = ""
# reddit = ""
# twitter = ""
# instagram = ""
# keybase = ""
# youtube = ""
