# The URL the site will be built for
base_url = "https://ergo.liquidthink.net"

title = "Alan Turing"
# a description; you can use markdown here if you like
description="\"*to develop the skill of correct thinking is in the first place to learn what you have to disregard. In order to go on, you have to know what to leave out.*\" \n -Kurt GÃ¶del"
default_language = "en"

highlight_theme = "solarized-light"
generate_rss = true
rss_limit = 20

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]
# theme options, (Submit an issue if any social network you may want is missing here: https://github.com/InsidiousMind/Ergo/issues)
profile = "profile.svg" # the name of the profile picture in static/img/
website = "liquidthink.net"
github = "insipx"
# gitlab = ""
twitter = "insipx"
# telegram = ""
# vk = ""
# linkedin = ""
email = "github@andrewplaza.dev"
# instagram = ""
# keybase = ""
# reddit = ""
# youtube = ""
color_themes = ["default", "dark"]
# comments settings
[extra.comments] # Optional
repo = "insipx/Ergo"
theme = "github-light"
label = "comment" # Optional
#issue_number = 1 # Specify either this or term
term = "pathname"
