name = "Ergo"
description = "A simple blog Theme focused on writing, inspired by svbtle"
license = "MIT"
homepage = "https://github.com/InsidiousMind/Ergo"
min_version = "0.4.1"
demo = "https://ergo.liquidthink.net"

[author]
name = "Andrew Plaza"
homepage = "https://code.liquidthink.net"
